### ISSUE TITLE
Android模拟器启动调用报错

### ISSUE THREAD

**Issue by fuxianwei** [netease-im/NERTC-Flutter-SDK#17]
打印错误如下：
`java.lang.UnsatisfiedLinkError: Can not load nertc_sdk ,Supported ABI[ x86_64 arm64-v8a ]Please use {libnertc_sdk.so or libnertc_sdk_x86_64.so} 
I/.app.flutter.i(22567): LinkError: 
I/.app.flutter.i(22567): dlopen failed: library "libnertc_sdk.so" not found
I/.app.flutter.i(22567): dlopen failed: library "libnertc_sdk_arm64-v8a.so" not found
I/.app.flutter.i(22567): dlopen failed: library "libnertc_sdk_armeabi-v7a.so" not found`

更多信息如下：
I/Logging (22567): EglBase14: SDK version: 32. isEGL14Supported: true
D/EGL_emulation(22567): eglCreateContext: 0x7bf8b60a0310: maj 3 min 0 rcv 3
I/.app.flutter.i(22567): Rejecting re-init on previously-failed class java.lang.Class<com.netease.lava.nertc.impl.NERtcImpl$SingletonHolder>: java.lang.UnsatisfiedLinkError: Can not load nertc_sdk ,Supported ABI[ x86_64 arm64-v8a ]Please use {libnertc_sdk.so or libnertc_sdk_x86_64.so} 
I/.app.flutter.i(22567): LinkError: 
I/.app.flutter.i(22567): dlopen failed: library "libnertc_sdk.so" not found
I/.app.flutter.i(22567): dlopen failed: library "libnertc_sdk_arm64-v8a.so" not found
I/.app.flutter.i(22567): dlopen failed: library "libnertc_sdk_armeabi-v7a.so" not found
I/.app.flutter.i(22567): 
I/.app.flutter.i(22567):   at void com.netease.lava.base.util.NativeLibLoader.loadLibrary(java.lang.String) (NativeLibLoader.java:61)
I/.app.flutter.i(22567):   at void com.netease.lava.nertc.impl.NERtcImpl.<init>() (NERtcImpl.java:307)
I/.app.flutter.i(22567):   at void com.netease.lava.nertc.impl.NERtcImpl.<init>(com.netease.lava.nertc.impl.NERtcImpl$1) (NERtcImpl.java:191)
I/.app.flutter.i(22567):   at void com.netease.lava.nertc.impl.NERtcImpl$SingletonHolder.<clinit>() (NERtcImpl.java:303)
I/.app.flutter.i(22567):   at com.netease.lava.nertc.impl.NERtcImpl com.netease.lava.nertc.impl.NERtcImpl.getInstance() (NERtcImpl.java:311)
I/.app.flutter.i(22567):   at com.netease.lava.nertc.sdk.NERtcEx com.netease.lava.nertc.sdk.NERtcEx.getInstance() (NERtcEx.java:52)
I/.app.flutter.i(22567):   at com.netease.nertcflutter.Messages$IntValue com.netease.nertcflutter.NERtcEngine.create(com.netease.nertcflutter.Messages$CreateEngineRequest) (NERtcEngine.java:286)
I/.app.flutter.i(22567):   at void com.netease.nertcflutter.Messages$EngineApi$-CC.lambda$setup$0(com.netease.nertcflutter.Messages$EngineApi, java.lang.Object, io.flutter.plugin.common.BasicMessageChannel$Reply) (Messages.java:2488)
I/.app.flutter.i(22567):   at void com.netease.nertcflutter.-$$Lambda$Messages$EngineApi$dxwYUpr9rrvDnvuF1BHDaUQvmZI.onMessage(java.lang.Object, io.flutter.plugin.common.BasicMessageChannel$Reply) (lambda:-1)
I/.app.flutter.i(22567):   at void io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (BasicMessageChannel.java:217)
I/.app.flutter.i(22567):   at void io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(io.flutter.embedding.engine.dart.DartMessenger$HandlerInfo, java.nio.ByteBuffer, int) (DartMessenger.java:295)
I/.app.flutter.i(22567):   at void io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(java.lang.String, int, io.flutter.embedding.engine.dart.DartMessenger$HandlerInfo, java.nio.ByteBuffer, long) (DartMessenger.java:322)
I/.app.flutter.i(22567):   at void io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$2j2MERcK825A5j1fv5sZ7xB2Iuo.run() (lambda:-1)
I/.app.flutter.i(22567):   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:938)
I/.app.flutter.i(22567):   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
I/.app.flutter.i(22567):   at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:201)
I/.app.flutter.i(22567):   at void android.os.Looper.loop() (Looper.java:288)
I/.app.flutter.i(22567):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7870)
I/.app.flutter.i(22567):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/.app.flutter.i(22567):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:548)
I/.app.flutter.i(22567):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1003)
E/flutter (22567): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(NoClassDefFoundError, java.lang.NoClassDefFoundError: com.netease.lava.nertc.impl.NERtcImpl$SingletonHolder, null, null)
E/flutter (22567): #0      EngineApi.create (package:nertc/src/internal/messages.dart:2085:7)
E/flutter (22567): <asynchronous suspension>
E/flutter (22567): #1      NERtcEngine.create (package:nertc/src/nertc_engine.dart:73:22)
E/flutter (22567): <asynchronous suspension>
E/flutter (22567): #2      _CallPageState._initRtcEngine (package:im_app/src/video/call_page.dart:140:5)
E/flutter (22567): <asynchronous suspension>
E/flutter (22567): 
D/EGL_emulation(22567): app_time_stats: avg=1030.41ms min=1.62ms max=20530.31ms count=20

**Comment by Nipuream** [comment]
在 app 目录下的 build.gradle 文件的 defalutConfig 中添加以下代码：

ndk {
    abiFilters+= listOf("armeabi-v7a","arm64-v8a")
}
